## Numpy练习

### 1. 创建一个长度为10全为0的一维数组，然后让第5个元素等于1。

In [1]:
import numpy as np
first_list = np.zeros(10)
print(first_list)
first_list[4] = 1
print(first_list)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 生成一个4X5和一个5X4的矩阵，并计算它们的乘积。

In [2]:
second_matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
first_matrix = second_matrix.reshape(4,5)
# print(first_matrix)
# print(second_matrix)
result = np.matmul(first_matrix,second_matrix)
print(result)

[[ 175  190  205  220]
 [ 400  440  480  520]
 [ 625  690  755  820]
 [ 850  940 1030 1120]]


### 3. 函数 f 定义如下，其中x是任意实数: 𝑓(𝑥)=(sin⁡(𝑥+1)/𝑒^𝑥 )(𝑥+1)/2，生成一个数组a∈𝑅^5，计算b = f(a)。

In [3]:
import math
def f(x):
    result = math.sin(x+1)/math.e**x * (x + 1)/2
    return result
a = [1,2,3,4,5]
b = []
for a_item in a:
    result = f(a_item)
    b.append(result)
print(b)


[0.33451182923926226, 0.028647774391702796, -0.07535795514973172, -0.043908276840928503, -0.005648060452762271]


### 4. 随机生成一个5行10列的矩阵，然后每行元素减去该行的平均值

In [4]:
a = np.random.rand(4,5)
print(a) 
for i in range(len(a)):
    row = a[i]
    row_average = np.mean(row)
    a[i] = row - row_average
print(a)

[[0.20046588 0.11435627 0.01449513 0.277741   0.21195624]
 [0.88058587 0.20011464 0.217408   0.79569204 0.14106385]
 [0.90013858 0.42662412 0.72235195 0.1235972  0.15819377]
 [0.32573365 0.86021908 0.06006714 0.13158752 0.15033487]]
[[ 0.03666298 -0.04944664 -0.14930777  0.11393809  0.04815334]
 [ 0.43361299 -0.24685824 -0.22956488  0.34871916 -0.30590904]
 [ 0.43395745 -0.03955701  0.25617082 -0.34258392 -0.30798735]
 [ 0.02014519  0.55463063 -0.24552131 -0.17400093 -0.15525358]]
